spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/sportdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG